### ISSUE TITLE
How do you quantize the float part?

### ISSUE THREAD

**Issue by rongzhao-zhang** [hossein1387/U-Net-Fixed-Point-Quantization-for-Medical-Image-Segmentation#4]
Hi, I read your paper titled "U-Net Fixed-Point Quantization for Medical Image Segmentation" and find it very interesting. But I cannot figure out how you quantize the fractional part. Concretely, from equation (3), which is x_f = abs(x) − floor(abs(x)); x_i = floor(abs(x)), we know that x_f is always in [0, 1) and strictly smaller than 1.0. Thus, the quantization of x_f, i.e., quantize(x_f, n) = (round(clamp(x_f, n) << n)) >> n, will always be zero since you right-shift an integer smaller than 2^n by n bits. Hence, will the float part of Eq. (4) (the "to_float_point" function) always be zero? Am I misunderstanding your equation? Can you help me to figure it out?

**Comment by hossein1387** [comment]
Thanks for your interest in my paper. I will give you an example withthe code available in my repo. Assume we want to quantize 3.126 to a fixedpoint data representation with Q4.4 format. The way I do it is:
(1) I will separate float and integer part.
(2) Then I will use 4 bits to represent the value of each portion.

For the first part, this is the code I use to split the [floating part](https://github.com/hossein1387/U-Net-Fixed-Point-Quantization-for-Medical-Image-Segmentation/blob/61233a7adc951d8d8b4beb04bab4360c10a08d90/UNET_GM_DATASET/UNET_Quant_Base/quantize.py#L33) and this to split the[ integer part](https://github.com/hossein1387/U-Net-Fixed-Point-Quantization-for-Medical-Image-Segmentation/blob/61233a7adc951d8d8b4beb04bab4360c10a08d90/UNET_GM_DATASET/UNET_Quant_Base/quantize.py#L34). I am basically subtracting the value from its floor to get the floating part and casting to int to get the integer part. So for our example, we have 3 for integer part and 0.126 for floating part. Lets convert both these values to binary assuming we have 32 bit to spare:

```
3      : 00000000000000000000000000000011
0.126  : 0.00100000010000011001000000000000

```
Now for the second part, [refer to this part](https://github.com/hossein1387/U-Net-Fixed-Point-Quantization-for-Medical-Image-Segmentation/blob/61233a7adc951d8d8b4beb04bab4360c10a08d90/UNET_GM_DATASET/UNET_Quant_Base/quantize.py#L13) to represent the value in the given representation. considering the above representation, and equation (3), I will first shift all value to left by the number of bits that I want to represent them:

```
48      : 00000000000000000000000000110000
2.016   : 10.000001000001100100000000000000

```
now lets round these numbers:

```
48      : 00000000000000000000000000110000
2.000   : 10.000000000000000000000000000000

```
and shift them back to the original representation:

```
3      : 00000000000000000000000000000011
0.125  : 0.00100000000000000000000000000000

```
