### ISSUE TITLE
How to use the inference function to get more output images?

### ISSUE THREAD

**Issue by ShaoCorn** [hossein1387/U-Net-Fixed-Point-Quantization-for-Medical-Image-Segmentation#5]

**Comment by ShaoCorn** [comment]
Hi, I have tried your great network and it trained well. But when I was using the "inference" function, I don't know how to utilize the trained model to inference more images, and it seems that when I was using "inference" mode, the network started to retrain the model (emdataset). Thanks!

**Comment by 1gzcdestiny1** [comment]
hi。I appreiate the code you provided.But i couln't find the code about showing the the network size,can you tell me what the method you did to show the size of the network after quantization?

**Comment by hossein1387** [comment]
Hi @ShaoCorn , could you please clarify which network and which quantization you are referring to? Also, could you please send me the command you are using for training? Have you changed any part of this repo locally that might break the training process?

**Comment by hossein1387** [comment]
@1gzcdestiny1 Please refer to https://github.com/hossein1387/U-Net-Fixed-Point-Quantization-for-Medical-Image-Segmentation/issues/6
