### ISSUE TITLE
plz help

### ISSUE THREAD

**Issue by 1gzcdestiny1** [hossein1387/U-Net-Fixed-Point-Quantization-for-Medical-Image-Segmentation#6]
hi,i appreciate the code you provided,but could you tell me what the method you did to show the model size after the quantification?i could't find the corresponding part in your code,thanks

**Comment by hossein1387** [comment]
Hi,

The quantization that I used is categorized under fake quantization. Meaning that I store 2/3/4 bit tensors into 32-bit float torch tensors. Hence, there is no real way to store the model after quantization. What I and many people do in such scenario is to guesstimate which more or less is accurate IF sub-eight bit quantization was fully supported by ML frameworks.
