### ISSUE TITLE
Inference time speedup estimate

### ISSUE THREAD

**Issue by felicitywang** [hossein1387/U-Net-Fixed-Point-Quantization-for-Medical-Image-Segmentation#7]
Hi, 
Thanks for the great work. I'm working on quantization for inference time speedup, but didn't seem to find any speed(up) reported in the paper. Is there any estimated value how much speedup (for inference) I can expect with an x memory reduction?

Thank you.

**Comment by hossein1387** [comment]
Hi

Well unfortunately there are not any ML framework (or HW for that matter) that support arbitrary precision integers. That is why I did not report any speedup in the paper.
